name: Build WhiteboxTools

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master  # Adjust to match your primary branch name

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macOS-latest, ubuntu-20.04, ]
        os: [ubuntu-22.04] #, windows-latest, macos-12, macOS-latest]
        python-version: ['3.11']

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
          
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install musl on linux
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install -y musl

      - name: Run build script linux
        if: startsWith(matrix.os, 'ubuntu')
        run: python build.py do_clean exclude_runner zip
      
      - name: Run build script non-linux
        if: startsWith(matrix.os, 'ubuntu') != true
        run: python build.py do_clean zip

      - name: Upload WBT
        uses: actions/upload-artifact@v4
        with:
          name: wbt-${{ matrix.os }}
          path: zip_file/*.zip
